#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
    path: /api/login_check
app_swagger_ui:
    path: /documentation
    methods: GET
    defaults: { _controller: api_platform.swagger.action.ui, area: default }
book_post_publication:
    path: /product/{id}/publication
    methods: ['POST']
    defaults:
        _controller: App\Controller\BookController::createPublication
        _api_resource_class: App\Entity\Book
        _api_item_operation_name: post_publication
